### PR TITLE
Refactor KVServiceManager on client to reduce code duplication

### PR DESCRIPTION
**Pull request by yankee42**
After refactoring the KVServiceManager on the server to reduce code duplication, I thought I should do the same for the client. I did so here.

I did run into trouble testing though. When running `./gradlew publishToMavenLocal`, I got:
```
> Task :signKotlinPublication FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':signKotlinPublication'.
> Cannot perform signing task ':signKotlinPublication' because it has no configured signatory
```
Maybe the [contributing guide](https://github.com/rjaros/kvision/blob/master/CONTRIBUTING.md) is outdated? Or did I do anything wrong?

### CODE REVIEW

**Comment by rjaros** [comment]
Yep, the contributing guide was outdated. I've updated. Generally use `./gradlew publishToMavenLocal -PSNAPSHOT=true` which automatically adds `-SNAPSHOT` suffix and skips signing tasks.

**Comment by rjaros** [comment]
You have lost the difference in web socket route name. It was `/kvws/*` and not `/kv/*`. Probably an additional parameter is needed.

**Comment by yankee42** [comment]
> Yep, the contributing guide was outdated. I've updated. Generally use `./gradlew publishToMavenLocal -PSNAPSHOT=true` which automatically adds `-SNAPSHOT` suffix and skips signing tasks.

Ah OK, so the step number 3 in the contribution guide is also obsolete then?



> You have lost the difference in web socket route name. It was `/kvws/*` and not `/kv/*`. Probably an additional parameter is needed.

OH, indeed. I will fix this.

**Comment by rjaros** [comment]
> Ah OK, so the step number 3 in the contribution guide is also obsolete then?

Unfortunately not. This version in Kotlin code still need to be synchronized manually. It would be great to have this automated, but I had no time to work on this.

**Comment by yankee42** [comment]
OK. I fixed the path issue and I also added a number of tests. However while writing the tests I noticed:
- What should actually happen in case of a conflict? (two functions with the same name. I think that's only possible in case of overloading. I guess that just should not be done, but maybe it is a good idea to generate an error in that case)
- The code checks if the passed function is of type `KFunction`. I think [that's impossible](https://kotlinlang.org/docs/js-reflection.html):
    > Kotlin/JS provides a limited support for the Kotlin reflection API. The only supported parts of the API are:
    >
    > - class references (::class ).
    > - KType and typeof() function.
    
    I think that means that `KFunction` is not supported in JS, so we can eliminate that?

**Comment by yankee42** [comment]
Oh and I got the problem that the tests do not run when executing `./gradlew test`. I put in an error to check by inserting an extra "X" in line 56 in the test. So if executed it would fail, but it does not. I am still struggeling a bit to understand the build configuration.

**Comment by rjaros** [comment]
> * I guess that just should not be done, but maybe it is a good idea to generate an error in that case)

Yes, it's not allowed. But the resulting code doesn't compile already, so there is no need for a runtime check.

> The code checks if the passed function is of type `KFunction`. I think [that's impossible](https://kotlinlang.org/docs/js-reflection.html):
> 
> > Kotlin/JS provides a limited support for the Kotlin reflection API. The only supported parts of the API are:
> > 
> > * class references (::class ).
> > * KType and typeof() function.
> 
> I think that means that `KFunction` is not supported in JS, so we can eliminate that?

It works differently for IR and legacy compiler backends. This part: `(function as? KFunction<*>)?.name` is working on IR. But it returns `null` for legacy. On the other hand this part: `function.toString().replace("\\s".toRegex(), "")` works for legacy (returns unique values for different functions) but doesn't work for IR. I don't know yet if your change (using `is` instead of a cast) is working as well - it must be tested first.

**Comment by rjaros** [comment]
> Oh and I got the problem that the tests do not run when executing `./gradlew test`. I put in an error to check by inserting an extra "X" in line 56 in the test. So if executed it would fail, but it does not. I am still struggeling a bit to understand the build configuration.

It failed on CI, which is using `check` task.

**Comment by yankee42** [comment]
OK, great, so I'll also run the check task locally :-). I also see that the test runs twice, once with legacy and once with IR. So that should do to test anything that might be different.

For me the `as?` call just had a little too many safe navigation operators... So I thought that the if/else structure is more readable. I think it should be equivalent. However if you prefer the former I'll be happy to revert this.

I cleaned up everything and also extracted the code that builds the function name from other location within the code, so that the call name generation is encapsulated and can be changed easily, should this ever become necessary.

There is one thing I noticed though:
```kotlin
class Example {
    suspend fun someFunSuspend() {}
    fun someFun() {}
}

class ExampleSpec {
    fun getCallName(function: Function<*>) =
        (function as? KFunction<*>)?.name ?: function.toString().replace("\\s".toRegex(), "")

    @Test // passes
    fun getCallName_equalsGetCallNameInline_ifFunctionIsNotSuspend() {
        assertEquals(getCallName(Example::someFun), getCallNameInline(Example::someFun))
    }

    @Test // This fails on IR
    fun getCallName_equalsGetCallNameInlineSupsend_ifFunctionIsNotSuspend() {
        assertEquals(getCallName(Example::someFun), getCallNameInlineSuspend(Example::someFun))
    }

    /*@Test // Compile time error
    fun getCallName_equalsGetCallNameInlineSuspend_ifFunctionIsNotSuspend() {
        assertEquals(getCallName(Example::someFunSuspend), getCallNameInline(Example::someFunSuspend))
    }*/

    @Test // passes
    fun getCallName_equalsGetCallNameInlineSuspend_ifFunctionIsSuspend() {
        assertEquals(getCallName(Example::someFunSuspend), getCallNameInlineSuspend(Example::someFunSuspend))
    }

    internal inline fun <T, reified RET> getCallNameInlineSuspend(
        noinline function: suspend T.() -> RET,
    ) = getCallName(function)

    internal inline fun <T, reified RET> getCallNameInline(
        noinline function: T.() -> RET,
    ) = getCallName(function)
}
```
So the thing is the test `getCallName_equalsGetCallNameInlineSupsend_ifFunctionIsNotSuspend`: It fails on IR only. It SHOULD not be any problem, as it should not happen that the function passed in is not a suspend function. However if this is somehow possible, this could cause headaches until the cause is found (just like I got a little bit of a headache while writing the tests...)

**Comment by rjaros** [comment]
I've tested these changes with both compiler backends and all example apps and all seems to work fine. 
Thanks once again!

**Pull request merged**
