### PR TITLE
refactor KVServiceManager: Extract common super class

### PR DESCRIPTION
**Pull request by yankee42**
The next big thing in my quest to eliminate code duplication the the KVServiceManager classes would be the `bind`-methods which are exactly the same for all classes. So In this PR as a first step I extract a common super class which contain all those `bind`-methods.

Then there are also the `getParameter`-methods, which are also all the same. Additionally there is the usage of Jackson's `ObjectMapper` and you said you might want to replace this with Kotlin serialization. So I also extracted `getParameter` together with the `ObjectMapper` into an encapsulated object. So if anyone wants to use anything other than Jackson, it is just a matter of supplying a different implementation in the constructor call.

Then I noticed a bug I introduced myself: I forgot to remove the GET-check from the generalized vert.x `bind` method. That would mean that vert.x won't accept GET calls at all. Not my intention. That is fixed in the third commit.

In the forth commit I also extract the route name generation and routeMapRegistry management into the common super class.

Finally in the fith commit I fix yet another error from a previous PR: A test ended up in the wrong module.

I still have a problem: The tests won't run when executing `./gradlew test`. According to what I have found, I should just add
```kotlin
tasks.withType<Test> {
    useTestNG()
}
```
to the gradle build file. However that has no effect. This is the first time ever that I work with gradle and it does leave me somewhat clueless. Do you know what's wrong?

### CODE REVIEW

**Comment by rjaros** [comment]
Thanks! It looks awesome!

I had to fix one issue because serialize and deserialize operations are currently not symmetrical for `String` class, and your change made them so. It comes from a subtle differences on the client side, which I don't want to mess with (at least not at the moment :-)

As for the tests, you just need to execute `check` task instead of `test` to run tests for all targets in the multiplatform module.

**Comment by rjaros** [comment]
And I've found another issue. We are hitting an old, unresolved compiler bug:
https://youtrack.jetbrains.com/issue/KT-22625
when accessing `protected val deSerializer` from web sockets protected inline `bind` methods. The code compiles but there is `IllegalAccessError` at runtime. I have to make `deSerializer` public.

**Comment by rjaros** [comment]
Merged to the main tree.

**Comment by rjaros** [comment]
I've replaced jackson with kotlinx.serialization. Unfortunately requirements of both libraries are quite different, so I had to change quite a lot of things, including your test code. Even the `ObjectDeSerializer` interface required changes which are strictly bound to the `kotlinx.serialization` serializers. It doesn't look so universal and clean anymore, but I'm afraid I just can't make it better. Feel free to take a look.
I've also unified serialization and deserialization of `String` class.

**Comment by yankee42** [comment]
I had a quick look and the problem I see is that the plan of the `ObjectDeSerializer` was, that the whole thing is configurable. So as user of the framework, you can override the default and say "but I want Jackson serialization" (or some completely different own serialization method) by providing it as constructor argument to the KVServiceBinder (ok, well, some more changes would need to be made, so that the user has the chance to provide those constructor args, but it should be possible to get there). The new parameter `serializer: KSerializer<T>` in the interface `ObjectDeSerializer` now introduces a hard dependency on Kotlin serialization and since we don't have access to the type information anymore, this also means that it will be much more difficult to implement different serializers.

This is something that already happened, because I wrote a custom serializer as part of the `KVServiceBinderTest` because I wanted the test to be independent of the used serialization provider.

BTW, you changed the test quite a bit. E.g. The code under test contains this snippet:
```kotlin
function.invoke(
    this,
    deserialize(it[0]),
    deserialize(it[1]),
    deserialize(it[2]),
    deserialize(it[3]),
    deserialize(it[4]),
    deserialize(it[5]),
)
```
I thought that all those numbers run into danger of getting messed up. So in case someone rewrites this and makes a typical copy an paste error:
```kotlin
function.invoke(
    this,
    deserialize(it[0]),
    deserialize(it[1]),
    deserialize(it[2]),
    deserialize(it[2]),
    deserialize(it[4]),
    deserialize(it[5]),
)
```
This might go unnoticed for some time (if the parameters with index 2 and 3 are of same type) until this causes some really strange bugs. So I thought about how I can test that all parameters arrive in correct order and I eventually came up with the `PARAM_X_FUN` in the test. Now these don't return all args anymore, but just the last args, making the test quite a bit weaker. Additionally the correct usage of the receiver of the handling functions is not tested anymore.

Arguably it might have been cleaner on my side, not to rely on this magic contract in the test service that returns the arguments as list, but rather use mocks plus call assertions.

I am not quite sure why you changed the test that much though. I don't see any obvious conflict with Kotlin serialization?

Another question: Isn't that a quite big breaking change? If I understand correctly, then users of the framework are now required to only use return types in their service methods that are compatible for Kotlin serialization? So this breaks quite a number of apps?

Here is an idea on how it might work out without changing the interface `ObjectDeSerializer`. I didn't test though if it might have other drawbacks. In case a `KType` is needed I think it should be OK to add an argument of type `KType`.

```kotlin
inline fun <reified T> ObjectDeSerializer.deserialize(str: String?) = deserialize(str, T::class.java)

fun kotlinxObjectDeSerializer(): ObjectDeSerializer = KotlinxObjectDeSerializer

private object KotlinxObjectDeSerializer : ObjectDeSerializer {

    val json = Json {
        ignoreUnknownKeys = true
        serializersModule = SerializersModule {
            // ...
        }
    }

    override fun <T> deserialize(str: String?, type: Class<T>): T =
        type.cast(if (str == null) null else json.decodeFromString(json.serializersModule.serializer(type), str))

    override fun serializeNonNullToString(obj: Any): String =
        json.encodeToString(json.serializersModule.serializer(), obj)
}
```

**Comment by rjaros** [comment]
> I am not quite sure why you changed the test that much though. I don't see any obvious conflict with Kotlin serialization?

The interfaces need to be properly typed. `Any` and `List<Any>` don't work. In fact I wasn't able to compile the code without all these changes.
 
> Another question: Isn't that a quite big breaking change? If I understand correctly, then users of the framework are now required to only use return types in their service methods that are compatible for Kotlin serialization? So this breaks quite a number of apps?

This was always the case, because kotlin serialization is used on the client side.

> Here is an idea on how it might work out without changing the interface `ObjectDeSerializer`. I didn't test though if it might have other drawbacks. In case a `KType` is needed I think it should be OK to add an argument of type `KType`.

Perhaps the `KType` is something I should think about. `Class` is not enough to get the correct serializer, but `KType` might work.

**Comment by yankee42** [comment]
> The interfaces need to be properly typed. `Any` and `List<Any>` don't work. In fact I wasn't able to compile the code without all these changes.

mhh ok, I see. A solution could be to use a class with the seven items as properties instead of a list... On the other hand: If the custom serializer could be brought back it should work as before, I guess...

> > Another question: Isn't that a quite big breaking change?[..]
> 
> This was always the case, because kotlin serialization is used on the client side.

oh, OK.

> > Here is an idea on how it might work out without changing the interface `ObjectDeSerializer`. I didn't test though if it might have other drawbacks. In case a `KType` is needed I think it should be OK to add an argument of type `KType`.
> 
> Perhaps the `KType` is something I should think about. `Class` is not enough to get the correct serializer, but `KType` might work.

Maybe something like this:
```kotlin
interface ObjectDeSerializer {
    fun <T> deserialize(str: String?, type: Class<T>, kType: KType): T
    // ...
}

@OptIn(ExperimentalStdlibApi::class)
inline fun <reified T> ObjectDeSerializer.deserialize(str: String?) = deserialize(str, T::class.java, typeOf<T>())
```
Maybe the `Class`-param could be omitted. However currently it is needed for safe casts.

**Pull request merged**
