### PR TITLE
Fix namespace issue

### PR DESCRIPTION
**Pull request by robert-cronin**
Rename 2 conflicting Options variables in the Charts and Tabulator packages to ChartOptions and TabulatorOptions respectively

### CODE REVIEW

**Comment by robert-cronin** [comment]
Quite a few commits I know, do you just test with `gradlew test` on your local machine?
I get the following error when I test on my local (Windows) machine, which is why I've had to use Travis CI to test once its uploaded
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for kotlinx-serialization-runtime-js@0.11.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'kvision-bootstrap'
npm ERR! notarget 
```

**Comment by rjaros** [comment]
You have just became a contributor :) Congrats :)

**Comment by rjaros** [comment]
As for the tests, I just run `gradlew test` on my machine, but I'm using Linux.

**Comment by rjaros** [comment]
I've tested this on my Win10 machine and it works without problems as well. The system configuration is the same as mentioned here: https://github.com/rjaros/kvision-examples/issues/5#issuecomment-489720803

**Comment by robert-cronin** [comment]
Great!  It's a good feeling :) I've got a few more ideas for KVision in the works,  you should see them over the next week or so

**Pull request merged**
