### PR TITLE
Revise bootstrap progress

### PR DESCRIPTION
**Pull request by yankee42**
I wanted to use a Bootstrap progress component in my project, however the implementation that ships with KVision did not help for my use case. I believe the following things could be improved:

- It should allow multiple progress bars within a single progress
- It should not force the usage of `Int`. At least `Double` (e.g. for values ranging from 0 to 1) would make sense, possibly even custom types
- Naming could be closer to the original Bootstrap names ("progress" for the entire construct, "progress bar" for each bar within the progress)
- It should handle formatting of a progress bar label in most cases automatically, so that if the status changes we do not need to call update the progress value and the content
- It should be more extendable for other purposes.

I implemented these things in this PR. Here is some sample usage with my new implementation:
```kotlin
p("Simple graph:")
progress(classes = setOf("w-100")) {
    progressNumeric(25)
}
p("Graph with bounds, percentage, multiple bars:")
progress(0, 10, classes = setOf("w-100")) {
    progressNumeric(4, FormatFractionContentGenerator(), setOf("bg-success"))
    progressNumeric(2, FormatFractionContentGenerator(), setOf("bg-danger"))
}
p("Graph with custom label:")
progress(0, 30, classes = setOf("w-100")) {
    progressNumeric(22, ContentGenerator { tag, value, bounds -> tag.content = "$value / ${bounds.max}" })
}
p("Graph with styled label:")
progress(0, 30, classes = setOf("w-100")) {
    progressNumeric(22, ContentGenerator { tag, value, bounds ->
        tag.content = "I have a tooltip"
        enableTooltip(TooltipOptions("I am the tooltip"))
    })
}
```
This results in:
image

This is work in progress. I still have a number of things to consider:
- I added the `AttributeDelegate` and the `CssClassPresent`. They seem useful to me, however maybe I missed something like this that already exists? If not, they are maybe better be put in another location for general use?
- I am a little suprised the external definitions for `Intl.NumberFormat` is not in Kotlin's standard library. I added those in the process here, however maybe I missed something and maybe it is better be put in a different location?
- I added the `Widget.hasCssClass`-method. It does seem useful and alternatives such as going via `getSnClass` seem to be overly complicated. Nevertheless: Is it OK to add this there? Should this also be added to the interface?
- The way I did it, it would be a breaking change. I think it should not be a problem to remodel the old `ProgressBar` to delegate to the new `Progress`, but how to best distinguish between the implementations? Move the new implementation to a new package? If so, which name? Rename the classes? To what?

Please let me know how you see this... Is this PR is welcome? What would need to be different? What do you think about the things listed above?

(And please bear with me in case I did anything stupid. I just started learning Kotlin&KVision a few days ago, coming from a Java&TypeScript&Angular Background)

### CODE REVIEW

**Comment by rjaros** [comment]
That's great work! Thank you.
You will have to give me some time to check all the code and answer your questions, but it's definitely great improvement.

**Comment by rjaros** [comment]
I've merged your PR to https://github.com/rjaros/kvision/tree/bootstrap_progress branch and made some changes:
- Removed your `ProgressBar` interface and restored the original `ProgressBar` component, to keep compatibility between minor releases. I've annotated the original component as `@Deprecated`, and I'll remove it in the next major release. For now, I've merged `value` property into `ProgressBarTag` abstract class and the interface wasn't used anywhere, so I think it should be ok.
- Moved `AttributeDelegate` class to `p.t.k.core` package and `NumberFormat.kt` to `p.t.k.utils` package for general use.
- Removed `CssClassPresent` and used more standard KVision way of handling CSS classes (`override fun getSnClass(): List<StringBoolPair>` method in `ProgressBarTag`).
- Added some methods and extensions to `Progress` class for better compatibility with the old component.
- Added `style: ProgressBarStyle` property for `ProgressBarTag` component (I like to have typesafe enum values instead of just string css classes) 
- Made some variance fixes for better handling of different Number types.
- Addes some kdoc and licence comments.

Please review my changes in the branch, and let me know if you think it's ok. Then I'll merge it to the main tree. Thank you once again for your work!

**Comment by yankee42** [comment]
> I've merged value property into ProgressBarTag abstract class and the interface wasn't used anywhere, so I think it should be ok.

Yes, that should be fine.

> Removed CssClassPresent and used more standard KVision way of handling CSS classes

I am still a little bit at odds with that system, as I haven't quite understood it's purpose.  Maybe you can bring some light to my thoughts?
1. Why `sn`? It took me quite some diving through the code, and now I believe `sn` = "Snapdom". However there is really not anything Snapdom'y about this? It is just a list of String/Bool-Pairs.
2. Why String/Bool pairs? As far as I have spotted the boolean is always `true`. In that case just a simpler `Set<String>` would be fine? I thought maybe it is consumed like this bei Snapdom, but the only consumer I found was that:
    ```kotlin
    inline fun snClasses(pairs: List<StringBoolPair>): Classes {
        return obj {
            pairs.forEach { (key, value) -> this[key] = value }
        }
    }
    ```
    And this function does not take any advantage of the `Pair`.    
3. Why the override system? The call through the chain of `super`-calls with each layer copying the list might be a slight performance burden, although I guess it is not that much, since we are talking about very small arrays. You added the `snClassCache`, but wouldn't it just be a lot simple to work with `addCssClass` and `removeCssClass`? This would also make accessors much simpler thanks to the possibility of just using a delegate.
4. Why does the `classes` Set on `Widget` exist in the first place, if it is not supposed be used, can it be removed?
    
    If so, should this not also apply to attributes? So should `getSnAttrs` be overriden instead of the delegate I wrote?


> Added style: ProgressBarStyle property for ProgressBarTag component (I like to have typesafe enum values instead of just string css classes)

I understand the motivation, however: These are just the bg-$color classes generated by bootstrap, they are not very specific to `progress`. [Bootstrap defines these colors for all theme-colors, plus `body`, `white` and `transparent`](https://github.com/twbs/bootstrap/blob/cfd00b5eeb7b7440afb3f115a66ea3c58e2e2d5d/scss/_utilities.scss#L454). So in default configuration this would be:
- .bg-primary
- .bg-secondary
- .bg-success
- .bg-danger
- .bg-warning
- .bg-info
- .bg-light
- .bg-dark
- .bg-body
- .bg-white
- .bg-transparent

So the question would be: Does it make sense for a more "global" enum `BackgroundColorClass` or similar to be used here rather than the local `ProgressBarStyle`? Of course when using scss directly, it is really easy to alter the `$theme-colors` array and thus cause the list above to change. I guess that will be not a super common use case, an in this case it would still be possible to fallback to standard classes. The coolest thing would be to generate the enum from scss, butI guess that would be a huge thing.

One thing I wonder about my own code after thinking about this for a while: The way I coded the `ContentGenerator` feels like "the Java way" (using an interface) to do it. Maybe it would have been more "the Kotlin way" (using functions) like this?:
```kotlin
typealias ContentGenerator<T> = (tag: Tag, value: T, bounds: Bounds<out T>) -> Unit

fun formatFractionContentGenerator(
    numberFormat: Intl.NumberFormat = pl.treksoft.kvision.utils.numberFormat {
        style = "percent"
    }
): ContentGenerator<Number> =
    { tag: Tag, value: Number, bounds: Bounds<out Number> ->
        tag.content = numberFormat.format(bounds.fraction(value.toDouble()))
    }

fun formatNumberValueContentGenerator(numberFormat: Intl.NumberFormat = Intl.NumberFormat()): ContentGenerator<Number> =
    { tag: Tag, value: Number, bounds: Bounds<out Number> ->
        tag.content = numberFormat.format(value)
    }
```

Something I noticed that you added is the unsubscribe-call in `dispose`. That is probably a good idea. However I wondered if it would not be better for readability to use a hook for that. I found that there even are hooks for that, but they... cannot easily be used for that. For that see #197

https://github.com/rjaros/kvision/blob/0529038b197b56dffd2ae40c0f3e36250b6b8398/kvision-modules/kvision-bootstrap/src/main/kotlin/pl/treksoft/kvision/progress/Progress.kt#L37
I guess it is a typo, that it is not "bound**s** of the progress".

https://github.com/rjaros/kvision/blob/0529038b197b56dffd2ae40c0f3e36250b6b8398/kvision-modules/kvision-bootstrap/src/main/kotlin/pl/treksoft/kvision/progress/Progress.kt#L92
When referring to "same parameters as X" then I think `@see X` would make sense, so that we get a link in the documentation.

https://github.com/rjaros/kvision/blob/0529038b197b56dffd2ae40c0f3e36250b6b8398/kvision-modules/kvision-bootstrap/src/main/kotlin/pl/treksoft/kvision/progress/ProgressBarTag.kt#L52
That's more of a side note or a question. Do you make it a rule, that every attribute has a comment? Because I think this (and some other) comments don't really add any information. I'd hope, that a property `style` on a progress bar represents the style of the progress bar.

**Comment by rjaros** [comment]
> > Removed CssClassPresent and used more standard KVision way of handling CSS classes
> 
> I am still a little bit at odds with that system, as I haven't quite understood it's purpose. Maybe you can bring some light to my thoughts?
> 
> 1. Why `sn`? It took me quite some diving through the code, and now I believe `sn` = "Snapdom". However there is really not anything Snapdom'y about this? It is just a list of String/Bool-Pairs.

`Sn` comes from Snabbdom, a virtual dom library used by KVision.

> 2. Why String/Bool pairs? As far as I have spotted the boolean is always `true`. In that case just a simpler `Set<String>` would be fine? I thought maybe it is consumed like this bei Snapdom, but the only consumer I found was that:
>    ```kotlin
>    inline fun snClasses(pairs: List<StringBoolPair>): Classes {
>        return obj {
>            pairs.forEach { (key, value) -> this[key] = value }
>        }
>    }
>    ```
>    And this function does not take any advantage of the `Pair`.

It's true, it could be just a `Set`. But this data structure is taken directly from Snabbdom API (https://github.com/snabbdom/snabbdom#the-class-module). Snabbdom allows the `false` value as well. It's not used in KVision at the moment, but it probably could in the future (and I definitely couldn't be sure it won't be needed, when I've designed this :-))

> 3. Why the override system? The call through the chain of `super`-calls with each layer copying the list might be a slight performance burden, although I guess it is not that much, since we are talking about very small arrays. You added the `snClassCache`, but wouldn't it just be a lot simple to work with `addCssClass` and `removeCssClass`? This would also make accessors much simpler thanks to the possibility of just using a delegate.

`addCssClass` and `removeCssClass` methods are designed as user API, to allow adding/removing additional css classes to components. But in many different components I need internal classes, connected directly to component design or component properties (like `progress-bar-striped` bound to `striped` or `animated` properties). Such classes are defined with `getSnClass()` method (and can't be removed by `removeCssClass`). There are some places where I've taken shortcuts and use `addCssClass` or `classes` constructor property for internal usage as well, but those are just bugs, which shouldn't be there.
 
> 4. Why does the `classes` Set on `Widget` exist in the first place, if it is not supposed be used, can it be removed?

It exists to keep those additional css classes.

>    If so, should this not also apply to attributes? So should `getSnAttrs` be overriden instead of the delegate I wrote?

It should and it does. I just didn't want to change too much of your code. And the `AttributeDelegate` class is nice and could be useful for users.
 
> > Added style: ProgressBarStyle property for ProgressBarTag component (I like to have typesafe enum values instead of just string css classes)
> 
> I understand the motivation, however: These are just the bg-$color classes generated by bootstrap, they are not very specific to `progress`. [Bootstrap defines these colors for all theme-colors, plus `body`, `white` and `transparent`](https://github.com/twbs/bootstrap/blob/cfd00b5eeb7b7440afb3f115a66ea3c58e2e2d5d/scss/_utilities.scss#L454). So in default configuration this would be:
> 
> * .bg-primary
> * .bg-secondary
> * .bg-success
> * .bg-danger
> * .bg-warning
> * .bg-info
> * .bg-light
> * .bg-dark
> * .bg-body
> * .bg-white
> * .bg-transparent
> 
> So the question would be: Does it make sense for a more "global" enum `BackgroundColorClass` or similar to be used here rather than the local `ProgressBarStyle`? Of course when using scss directly, it is really easy to alter the `$theme-colors` array and thus cause the list above to change. I guess that will be not a super common use case, an in this case it would still be possible to fallback to standard classes. The coolest thing would be to generate the enum from scss, butI guess that would be a huge thing.

The current set of enum values is a remnant of KVision 1 and Bootstrap 3. It just never got updated to Bootstrap 4 full capabilities. It could be global enum of course, if it could be used in different places as well.

> One thing I wonder about my own code after thinking about this for a while: The way I coded the `ContentGenerator` feels like "the Java way" (using an interface) to do it. Maybe it would have been more "the Kotlin way" (using functions) like this?:
> 
> ```kotlin
> typealias ContentGenerator<T> = (tag: Tag, value: T, bounds: Bounds<out T>) -> Unit
> 
> fun formatFractionContentGenerator(
>     numberFormat: Intl.NumberFormat = pl.treksoft.kvision.utils.numberFormat {
>         style = "percent"
>     }
> ): ContentGenerator<Number> =
>     { tag: Tag, value: Number, bounds: Bounds<out Number> ->
>         tag.content = numberFormat.format(bounds.fraction(value.toDouble()))
>     }
> 
> fun formatNumberValueContentGenerator(numberFormat: Intl.NumberFormat = Intl.NumberFormat()): ContentGenerator<Number> =
>     { tag: Tag, value: Number, bounds: Bounds<out Number> ->
>         tag.content = numberFormat.format(value)
>     }
> ```

I don't really have an opinion on that. I'm not a Kotlin purist :-)
 
> That's more of a side note or a question. Do you make it a rule, that every attribute has a comment? Because I think this (and some other) comments don't really add any information. I'd hope, that a property `style` on a progress bar represents the style of the progress bar.

I try to have comment for every public API element, even if those comments are often meaningless (and I know they are). The generated API documentation looks better (visually) this way. And I believe that someone, somewhere will try to correct these comments one day :-)

**Comment by yankee42** [comment]
> I just didn't want to change too much of your code.

I think you should really not hesitate to change anything that is not inline with the design of KVision. I think that breaking the underlying design is very harmful, I have just started to get to know a tiny bit of KVision, while you know it inside out and if I did stupid things, because I did not understand the design, than you should really say "no".

> addCssClass and removeCssClass methods are designed as user API, to allow adding/removing additional css classes to components.

OK, I see. I admit I don't really see the advantage, but of course I'll respect the design decision. I thought a little bit on how to make this a little more simpler... There are two ideas that come to mind:

1. The declarative way
    ```kotlin
    interface CssClassRegistry {
        fun add(className: String, getter: () -> Boolean)
        fun add(className: String)
        fun add(classNameGetter: () -> String?)
    }
    
    class CssClassRegistryImpl : CssClassRegistry {
        private val registry: MutableSet<() -> String?> = mutableSetOf()
    
        override fun add(className: String, getter: () -> Boolean) {
            registry.add { if (getter()) className else null }
        }
    
        override fun add(className: String) {
            registry.add { className }
        }
    
        override fun add(classNameGetter: () -> String?) {
            registry.add(classNameGetter)
        }
    
        fun getClasses() = registry.mapNotNull { it() }
    }
    
    // Add to `Widget`:
    class Widget {
        /* ... */
        private val _cssClassRegistry = CssClassRegistryImpl()
        private val cssClassRegistry: CssClassRegistry
            get() = _cssClassRegistry
        // Actually while already on it, I would stop using the `List<StringBoolPair>`. It is not needed and the new
        // system would allow to bring it back at any time without changing the public API. However for demo I leave it:
        private fun getSnClassInternal(): List<StringBoolPair> = _cssClassRegistry.getClasses().map { it to true }
    }
    
    // Excerpt from `ProgressBarTag`:
    class ProgressBarTag {
        init {
            cssClassRegistry.add("progress-bar")
            cssClassRegistry.add { style?.className }
            cssClassRegistry.add("progress-bar-striped") { striped || animated }
            cssClassRegistry.add("progress-bar-animated") { animated }
        }
    }
    ```
2. Stay with the current approach of overriding, but use a custom interface:
    ```kotlin
    interface ClassSet {
        fun add(value: String)
    }
    
    class ClassSetImpl : ClassSet {
        val classSet: MutableSet<String> = mutableSetOf()
        
        override fun add(value: String) {
            classSet.add(value)
        }
    }
    
    class ProgressBarTag {
        override fun getSnClass(classSet: ClassSet) {
            super.getSnClass(classSet)
            classSet.add("progress-bar")
            style?.let {
                classSet.add(it.className)
            }
            if (striped || animated) {
                classSet.add("progress-bar-striped")
            }
            if (animated) {
                classSet.add("progress-bar-animated")
            }
        }
    }
    ```
Advantages of the first option: 
- Compact definition
- No forgotten super calls

Advantages of the second option:
- Program stays in full command. E.g. omitting super class is still possible.

Advantages of both:
- Easier to extend and change: The interfaces `CssClassRegistry` / `ClassSet` can easily be extended for more powerful features if needed without the need to change the public API
- Easier to change: You said you are not using the possibility to set a pair to false, but just because it might be needed at some point in the future, everyone needs to create those Pair objects. The two approaches above would just encapsulate that problem away. In case you ever need to return to the pairs, you can do so without changing the public API.
- Better performance: No need to copy the full list on each layer passing through the component hierarchy.

Does this sound interesting to you? If yes, I'll try to actually implement one of those. However... I just did some thinking sports, I don't really want to throw over the design if the way it is is how you like it. In the end this is just random thoughts which crossed my mind and I had some fun thinking about.

> The current set of enum values is a remnant of KVision 1 and Bootstrap 3. It just never got updated to Bootstrap 4 full capabilities. It could be global enum of course, if it could be used in different places as well.

I thought about this for a bit how this could be done. One option:
```kotlin
interface CssClass {
    val className: String
}

/**
 * A marker interface that documents that this CSS-Class is a bootstrap background color
 */
interface BootstrapBackgroundColor : CssClass {
}

/**
 * The default background colors that come with vanilla bootstrap
 */
enum class DefaultBackgroundColors : BootstrapBackgroundColor {
    PRIMARY,
    SECONDARY,
    SUCCESS,
    DANGER,
    WARNING,
    INFO,
    LIGHT,
    DARK,
    BODY,
    WHITE,
    TRANSPARENT,
    ;

    override val className: String = "bg-${name.toLowerCase()}"
}
```
Has everything in there:
- All default values are defined as enum and can be accessed easily
- By requiring the type `BootstrapBackgroundColor` you can exactly mark what you expect in parameter lists
- In case of custom themes one can "extend" the enum by creating another enum that implements `BootstrapBackgroundColor`.

Then I found the class `BsBgColor`... So this does already exist. So maybe just use this enum? However the `className` in `BsBgColor` is internal, it would need to be public for that. But that should not be a problem? I wonder if it makes sense to use the construct with the interface though, to keep things extendable...

> I don't really have an opinion on that. I'm not a Kotlin purist :-)

Well, the advantage would be, that the code is a little shorter. So instead of `progressNumeric(22, ContentGenerator { tag, value, bounds ->... })`  it would be `progressNumeric(22, { tag, value, bounds ->... })`.

So... This has gotten longer than I intended. In case you think I am getting myself a little to much into the details, just give me a note and I try to keep it more basic.

How do we best continue? Should I make PRs to the `bootstrap_progress` or do you want to make changes yourself? (Or in case you want to go ahead with the current state, that is of course fine as well).

**Comment by rjaros** [comment]
> Does this sound interesting to you? If yes, I'll try to actually implement one of those. However... I just did some thinking sports, I don't really want to throw over the design if the way it is is how you like it. In the end this is just random thoughts which crossed my mind and I had some fun thinking about.

Your code does not take into account one very important thing - calling the `refresh()` method. In KVision all state is dynamic. When you add css class (or do literally any other change) , the `Widget.refresh()` have to be called. And you can't do this when delegating those parts to external classes/interfaces. You would have to pass `this` reference to these classes and that would make the whole decoupling worthless. So in my opinion such changes would require too much work and the positive effects would be limited.

> Then I found the class `BsBgColor`... So this does already exist. So maybe just use this enum? However the `className` in `BsBgColor` is internal, it would need to be public for that. But that should not be a problem? I wonder if it makes sense to use the construct with the interface though, to keep things extendable..

You are absolutely right. `BsBgColor` should be used. It's in the same module, so there is no need to drop the internal modifier.
I've already commited a fix to the branch. 
.
> > I don't really have an opinion on that. I'm not a Kotlin purist :-)
> 
> Well, the advantage would be, that the code is a little shorter. So instead of `progressNumeric(22, ContentGenerator { tag, value, bounds ->... })` it would be `progressNumeric(22, { tag, value, bounds ->... })`.

But as you have created a `fun interface`, you can use plain lambda right now :-)

> How do we best continue? Should I make PRs to the `bootstrap_progress` or do you want to make changes yourself? (Or in case you want to go ahead with the current state, that is of course fine as well).

I'll merge the current state of the branch to the main tree later today. 
Then, I will be happy with any new feedback :-)

**Comment by yankee42** [comment]
> Your code does not take into account one very important thing - calling the refresh() method.

That is taken care of by the `refreshOnUpdate` delegate, is it not? The proposals were only targeting the `getSnClass`-method, nothing more. And that method did not call refresh either, but rather was called by refresh...

**Comment by rjaros** [comment]
Yep, I haven't understood your proposal correctly. I like the second approach with a `ClassSet`. I probably should implement something similar at the beginning, instead of struggling with `List<StringBoolPar>.toMutableList()` all over the place. The same goes to `getSnAttrs()` and `List<StringPair>`. 

Now it will be quite a lot of work to refactor all the components, but feel free to contribute if you like :-)

**Pull request merged**
