### PR TITLE
Bump leaflet to v1.8.0

### PR DESCRIPTION
**Pull request by aSemy**
A new version of Leaflet is out. I'm working through and checking for updates. I'm opening this PR early to share progress.

I'm also using the opportunity to go through and add more documentation, copied from the Leaflet docs site.

The TypeScript types aren't available yet, but they're not necessary. They would be helpful so the API changes are more clear. I haven't seen any changes yet.

I also propose removing the deprecated functions in `MapsCompat.kt` in this update.

- [x] remove compatibility functions

I'm going through the Leaflet docs and checking for changes. Here's a checklist of the files I've checked so far.

- [x] leaflet/control
  - [x] Control
  - [x] Attribution
  - [x] Layers
  - [x] Scale
  - [x] Zoom
- [x] leaflet/core
  - [x] Class
  - [x] Handler
- [x] leaflet/dom
  - [x] Draggable
  - [x] DomUtil
- [ ] leaflet/events
  - [ ] eventHandlerFns.kt
  - [ ] leafletEvents.kt
  - [ ] Evented
  - [ ] LeafletEventHandlerFnMap
- [x] leaflet/geo
  - [x] Coords
  - [x] CRS
  - [x] LatLng
  - [x] LatLngBounds
  - [x] Projection
- [x] leaflet/geometry
  - [x] Bounds
  - [x] Point
- [x] leaflet/layer
  - [x] marker/
    - [x] DivIcon
    - [x] Marker
    - [x] Icon
  - [x] overlay/
    - [x] DivOverlay
    - [x] ImageOverlay
    - [x] Popup
    - [x] SVGOverlay
    - [x] Tooltip
    - [x] VideoOverlay
  - [x] tile/
    - [x] InternalTiles.kt
    - [x] GridLayer
    - [x] TileLayer
    - [x] WMS
  - [x] vector/
    - [x] Canvas
    - [x] Circle
    - [x] CircleMarker
    - [x] Path
    - [x] Polygon
    - [x] Polyline
    - [x] Rectangle
    - [x] Renderer
    - [x] SVG
  - [x] styleFunction.kt
  - [x] FeatureGroup
  - [x] GeoJSON
  - [x] InteractiveLayerOptions
  - [x] Layer
  - [x] LayerGroup
- [x] leaflet/map
  - [x] mapPanes.kt
  - [x] PanOptions.kt
  - [x] LeafletMap
- [x] callback.kt
- [x] unionAliases.kt

### CODE REVIEW

**Comment by aSemy** [comment]
> We are generally following semantic versioning, so in my opinion we should not remove backward compatibility functions until next major release (6.0). Do you agree?

Ah right, that makes sense. By that measure, the changes in Leaflet 1.8.0 (there are changes to methods and properties) mean that this PR should be in a major release, so the deprecated functions can go too.

SemVer aside, the compatibility functions have been deprecated for almost 5 months. I think that everyone should have migrated by now, so it's safe to remove them.

**Comment by rjaros** [comment]
OK

**Comment by rjaros** [comment]
Hi, how is the update going? Need some help? 
I plan to release the new version and would love to see Leaflet updated :-)

**Comment by aSemy** [comment]
Hi @rjaros, I got a bit bored of checking the code against the docs, and I was hoping that there would be an update for https://www.npmjs.com/package/@types/leaflet that would help. It doesn't look like that's in progress though.

Some of the types I wasn't sure how to update. Like the files under leaflet/events , they don't seem to have a direct equivalent, I can't remember why those are there. But I'll come back to those later.

I also had an idea for testing Leaflet, inspired by the types/leaflet project - I'll just make some tests that confirm that the bindings don't break https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/leaflet/leaflet-tests.ts

I've got a few hours free now, so I'll work on it. I hope that I'll get most of the 'easy' types updated, and maybe some tests. 

How soon would you like to make a release?

**Comment by rjaros** [comment]
I was hoping make a release over the weekend. 
I'm curious if the changes in 1.8 break current code (1.8.0 is automatically upgraded).

**Comment by aSemy** [comment]
Ah that's great, it would be cool to use it as soon as this weekend. I'll try and get things finished before Sunday.

> I'm curious if the changes in 1.8 break current code (1.8.0 is automatically upgraded).

It probably won't break totally. Some of the bindings might be incorrect, but then I think some of them were already incorrect!

**Comment by aSemy** [comment]
Alright, I think the externals have been updated now, except for the leaflet/events package. That's really confusing to look at, so I'm happy to just cross my fingers and hope it works. The rest of it should all work fine. 

That said, I haven't done any testing on my machine - I get an error during compilation

```
A problem occurred configuring project ':kvision-assets'.
> Could not resolve all files for configuration ':kvision-assets:classpath'.
   > Could not resolve dev.petuska:npm-publish:2.1.2.
     Required by:
         project :kvision-assets > dev.petuska.npm.publish:dev.petuska.npm.publish.gradle.plugin:2.1.2
```

---

I tried implementing some tests (along the lines of the [types/leaflet tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/leaflet/leaflet-tests.ts). I was hoping that if I tried to use a external with a wrong name, then it would throw an error. Then writing tests to make sure the externals were defined correctly would be pretty easy. But if I purposefully mis-defined an external property, the test still passed...

```kotlin
val map = Maps {
    width = 300.px
    height = 600.px
    configureLeafletMap {
        setView(LatLng(0, 0), 11)
        options.apply {
            crs = CRS.Simple
            // I changed the name of this option, so it compiles, but the test still works
            preferCanvasWRONG = true
        }
    }
}
root.add(map)
map.leafletMap { fitBounds(polyline.getBounds()) }
val element = document.getElementById("test")!!
// I wanted it to show an error, but it works as expected
println(element.innerHTML)
```

So for now

**Pull request merged**
