### PR TITLE
Add momentjs wrapper to kvision-modules

### PR DESCRIPTION
**Pull request by robert-cronin**

### CODE REVIEW

**Comment by robert-cronin** [comment]
This is the momentjs wrapper, I wasn't sure which tests to perform since I can't user DomSpec and I'm a bit of a newbie when it comes to kotlinjs testing! let me know if you think there is anything lacking from the PR.
This will also solve issue #39 when users choose to include the moment module.

**Comment by rjaros** [comment]
There are a few things to be clarified but I haven't tested it yet. 

1. You are creating an external class `pl.treksoft.kvision.moment.js.Moment` with two external methods taking Kotlin enum as parameters. Are you sure it will work? I would expect a call `m.format(FormatDisplayOption.MonthM)` will be translated to something like `m.format(MonthM)` or `m.format("MonthM")` in javascript, but not `m.format("M")` as it should. Maybe you should just leave these parameters as Strings?

2. Webpack configuration `webpack.config.d/moment.js` should be copied to all the templates in the kvision-examples repository (or even all example projects). As far as I know this configuration inside the module itself won't be used when building an application. It is probably used only when running tests.

**Comment by rjaros** [comment]
Delete the moment.js package description from `Module.md` and all should be ok.

**Comment by rjaros** [comment]
Delete the js package description from `Module.md` and all should be ok.

**Comment by robert-cronin** [comment]
> Delete the moment.js package description from `Module.md` and all should be ok.

done :)

**Pull request merged**
